### ISSUE TITLE
`set-output` Deprecated

### ISSUE THREAD

**Issue by SCP-017** [termux/upload-release-action#1]
The `set-output` command is deprecated and will be disabled soon. Please upgrade to using Environment Files. For more information see: https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands

**Comment by thunder-coding** [comment]
Thanks for reporting. documentation fixed in 1389ea7df0e1a2b5bf9dabc38a413c299eb34ead

**Comment by SCP-017** [comment]
@thunder-coding 

Finally, I'm very thankful for this update...

Advance Happy New Year bro...

**Comment by thunder-coding** [comment]
Happy to see that my open source contributions could help someone :)
