### ISSUE TITLE
Retry support

### ISSUE THREAD

**Issue by isage** [termux/upload-release-action#3]
Github likes to throw ECONNRESET sometimes, so it would be good to have retry support. 
See https://github.com/svenstaro/upload-release-action/issues/62

**Comment by thunder-coding** [comment]
I don't see any of those errors in https://ithub.com/termux/termux-packages. (The only place which I monitor and know uses this action). Can you share a recent action run which was stopped due to this error?

Also for such network error and similar, I'll have to look into what specific error is raised so as to target that only instead of also catching all sorts of errors. The documentation does not seem t be very specific about this though

**Comment by isage** [comment]
We're having it sometimes with svenstaro action (we're currently looking where to migrate from it)
But it isn't really descriptive https://github.com/vitasdk/packages/actions/runs/3792125068/jobs/6448313436

**Comment by thunder-coding** [comment]
It seems like the error is very consistent when uploading lots of files. I grepped through all the source (including node_modules) for the latest release of this repository (I'm talking about this fork) for "Server Error". Did not find any exact string that matches the error. Can you try switching to this action, in case it does make any difference? Maybe the error message may change and can help

**Comment by isage** [comment]
Yeah, sure.
https://github.com/vitasdk/packages/pull/251 as soon as this merged.
We also sometimes hit api rate limit with artifacts upload, which is strange, sine with token it should be 5000 and is more that enough for whole workflow. So some kind of descriptive error (or dumping response headers) would be nice too, to allow to debug such cases.

**Comment by isage** [comment]
Huh. So, https://github.com/isage/packages/actions/runs/3799384974
it hits api rate limit. Yet, available calls before action is 
```
"core": {
      "limit": 1000,
      "used": 48,
      "remaining": 952,
      "reset": 1672308195
    },
```

**Comment by isage** [comment]
Ok, looks like we got ECONNRESET <https://github.com/vitasdk/packages/actions/runs/3812070202/jobs/6485261991>
Or maybe something else, since it's hard to tell from `Error: Server Error`

**Comment by thunder-coding** [comment]
> Ok, looks like we got ECONNRESET <https://github.com/vitasdk/packages/actions/runs/3812070202/jobs/6485261991>
> Or maybe something else, since it's hard to tell from `Error: Server Error`

Can you try enabling debug logging for GitHub Actions. See https://docs.github.com/en/actions/monitoring-and-troubleshooting-workflows/enabling-debug-logging. Hope it helps find the actual problem.

**Comment by isage** [comment]
I don't have required access, but i've asked maintainer to do so

**Comment by isage** [comment]
https://github.com/vitasdk/packages/actions/runs/3895533347/jobs/6651429809
this is strange, it's still just says "Server error" even with debug.

**Comment by isage** [comment]
Haven't had that issue for a long time now, so i'll close for now
