### ISSUE TITLE
Api overuse

### ISSUE THREAD

**Issue by isage** [termux/upload-release-action#5]
1)  https://github.com/termux/upload-release-action/blob/master/src/uploadToRelease.ts#L29
By default, listReleaseAssets returns 30 items per page. We have 124 assets, so that's 5 pages => 5 api calls by paginate. And that's per artifact.
This can be raised to 100 per page, thus lowering to just 2 api calls per artifact

2) Maybe listReleaseAssets can be run and cached once before starting upload. Though, that'll fail if you somehow sequentially  upload two artifacts with same name. So maybe config flag to enable caching?

**Comment by thunder-coding** [comment]
Can you try v4.0.2. I've attempted to fix the issue. I hope it does make difference

**Comment by isage** [comment]
Thanks, that was fast. Already testing.

**Comment by isage** [comment]
Yep, that definitely helped.
Some stats:
Before action run: `"used": 116`
After action run: `"used": 488,`
